### ISSUE TITLE
🚀 Feature: iFrame Embed Customization

### ISSUE THREAD

**Issue by luizgununes** [novuhq/novu#1041]
### 🔖 Feature description

It would be nice if it was possible to customize the colors, text, font, etc.

### 🎤 Why is this feature needed ?

In my use case, my software has a color palette that doesn't match Novu colors. It would be interesting to change the language too, because my software is in Portuguese, for example.

### ✌️ How do you aim to achieve this?

This functionality would be of great help not only to me but to many other users.

### 🔄️ Additional Information

I tried to inject a file into the iFrame but i've failed. There's no way to do it. Maybe a HTML injection instead of iFrame would be more easy to customize.

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by scopsy** [comment]
Right now we only support theme customization on the notification center component as written https://docs.novu.co/notification-center/react-components#customizing-the-notification-center-theme

What we will need to do it to provide the same interface for the embed widget aswell. Thanks for suggesting this @luizgununes

**Comment by robjean9** [comment]
Create an embed script that inject directly in HTML the Novu Notification Center instead of iFrame would be amazing!

One possible solution to pass custom CSS to iFrame could be add a variable on `novu.init` to pass a css string to the iFrame. This requires that `novu.init ` accept this variable in the iFrame using the postMessage() and add the css as a `style` tag on the iFrame.

**Comment by oba2311** [comment]
@robjean9 / @luizgununes  interested in working on this one?
