### ISSUE TITLE
🐛 Bug Report: Why am I being forced to key in full name?

### ISSUE THREAD

**Issue by lawweiliang** [novuhq/novu#1186]
### 📜 Description

![image](https://user-images.githubusercontent.com/34936929/188151164-f3cc9852-7296-4f34-baa1-4151214fc8f6.png)

### 👟 Reproduction steps

1. Sign in to the https://web.novu.co/ as admin and invite A.
2. Then, accept the invitation using email A.
3. It will direct you to this page 
![image](https://user-images.githubusercontent.com/34936929/188150833-638197e7-3d86-4f01-9f0f-156149f6c7aa.png)

### 👍 Expected behavior

I can put whatever name that I prefer make the changes inside the system.

### 👎 Actual Behavior with Screenshots

Put in any name. Be it with "abc" or "cde".

### 💻 Operating system

Windows

### 🤖 Node Version

v.16.14.1

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by scopsy** [comment]
Hi @lawweiliang we require the full name because we might need with some personalization usages inside the web platform later. If you prefer to stay anonymous you could always use some nickname in this field, just make sure to include a space in between. For example: "Weiliang Developer"

Closing this for now
