### ISSUE TITLE
Standardize Naming Convention of the repository

### ISSUE THREAD

**Issue by lawweiliang** [novuhq/novu#1190]
![image](https://user-images.githubusercontent.com/34936929/188158008-6064a8ad-2195-4b89-84e5-51ff8cb3452e.png)

Both are correct, just stick with one.
Whether you want a  dash "-" or without the dash?

Do not look down on all this small nitty gritty stuff. 
The coding standard is the rule that every developer needs to follow. You need to craft this as early as possible and put it in the contribution section. You will thank me later when the system is getting huge.  😃 

Buddies, no worries. I list out all the problems first then we eat the "worms and bugs" together. Hehe

**Comment by scopsy** [comment]
Hi @lawweiliang thank you for opening this issue! We are using dashes, just the envirocheck repository is the name of the project itself. So it's not 2 separate words but a name of the actual project. So other than envirocheck every thing will be with dashes :) Did you found other places where we used other convention rather than dashes?

**Comment by lawweiliang** [comment]
@scopsy 

Oh I see.  I think this one is the project name as well. 
![image](https://user-images.githubusercontent.com/34936929/188327108-ff5085fe-1da3-4ad7-8639-3ce019633eeb.png)

In that case, you might close this issue. Brother.
