### ISSUE TITLE
[NV-186] - Move provider ID outside of provider implementation

### ISSUE THREAD

**Issue by scopsy** [novuhq/novu#14]
Currently, the id is part of the provider implementation, this can cause duplication and limits the API user to register multiple providers from the same types but different keys.

### **The new API**

```
notifire.registerProvider('<ID>', new SendgridEmailProvider({...}))
```

This removes the `id` key from the `IProvider` interface when implementing and attaching it only during registration.\
Instead of the `id` under the provider, a new key `name` will be added to be used to distinguish different providers for logging purposes later.

The `id` in the `registerProvider` the method can be optional, and we can fall back to `name` on the provider as an id for simpler use-cases

**Comment by davidsoderberg** [comment]
Is this something I can do?

**Comment by scopsy** [comment]
@davidsoderberg yeah sure, in terms of the API was thinking more about the passport.js approach, where the id is not mandatory in terms of the interface. When not passed the internal identifier from the provider is used. If the `id` was specified it is used instead.

**Comment by davidsoderberg** [comment]
@scopsy I think I need to get this clarified a bit before I start with it so here are some questions 😄 
1. Should the `registerProvider` look like this:
```notifire.registerProvider('<ID>', new SendgridEmailProvider({...}))```
or like this:
```notifire.registerProvider(new SendgridEmailProvider({...}), '<ID>')```
The first one would break the API... Should I go with the second one to not break the API?
2. In `ProviderStore` the `providers` property could be a map instead of an array that would make sure that only one provider with the same id is registered at the same time? This could break peoples code because method `getProviderById` would always right now find the first registered provider. But it can also introduce bugs in peoples application because they expects the newest registered provider but gets the oldest of them. What do you think?
3. Do we need to add the name property to each provider or could we just keep id?

**Comment by davidsoderberg** [comment]
Also please assign me to this one :)

**Comment by scopsy** [comment]
Sure! @davidsoderberg 

1. We can go with the first one and make it optional. so that both options will work, we can check the param type for string to get that. that's how passport and a lot of libraries are doing it. So it won't break the API's
```
notifire.registerProvider('<ID>', new SendgridEmailProvider({...}))
notifire.registerProvider(new SendgridEmailProvider({...}))
```
2. That's a good point, we definitely can do a Map there. How do you think about finding a provider by a channel in that case? 
3. I think we can add a name as it describes better the use of it and to avoid confusion with the `id` from the store.

**Comment by nevo-david** [comment]
@scopsy can we close this?
