### ISSUE TITLE
🚀 Feature:  i18n - Mandarin Support 

### ISSUE THREAD

**Issue by bhattabhi013** [novuhq/novu#1751]
### 🔖 Feature description

Adding Mandarin language support.

### 🎤 Why is this feature needed ?

For Chinese people who are not familiar with English.

### ✌️ How do you aim to achieve this?

Add a new translation file here: packages/notification-center/src/i18n/languages. You can follow the en.ts example.
Add your translation import to the TRANSLATIONS object at packages/notification-center/src/i18n/lang.ts
Add the language code to the I18NLanguage type in the lang.ts file.
Updating /docs/docs/notification-center/react-components.md for the language added.
Submit a PR

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

**Comment by jainpawan21** [comment]
Hi, we already have chinese support. Is mandarine different from chinese?

**Comment by ArshErgon** [comment]
@jainpawan21 short answer: Mandarin is a form of the Chinese language, just like Arabic is different in many countries, there will be some words same in both but not all things will be the same.
I'd like to work on this issue, Assign this issue to me

**Comment by oneknucklehead** [comment]
can i work on this issue?

**Comment by jainpawan21** [comment]
@scopsy Shall we consider this language?

**Comment by p-fernandez** [comment]
@ArshErgon, unfortunately mandarin support can't be added right now as we can only work with ISO 639-1 language codes (2 letters). Mandarin is present in ISO 639-3 as `cmn`. When we would be able to support that ISO specification for languages we will announce and let the community provide translations for the languages supportes with that specification.
I am closing this issue because of this, @bhattabhi013.
