### ISSUE TITLE
🐛 Bug Report: Self-hosted Invite functionality does not work

### ISSUE THREAD

**Issue by jfemia** [novuhq/novu#1971]
### 📜 Description

The invite functionality doesn't work in a self-hosted environment. Attempting to invite a user results in a HTTP 500 response from the invite API.

It appears the implementation of the invite usecase instantiates a `Novu` client but does not pass the configured `API_ROOT_URL`, so it defaults to calling the hardcoded cloud URL, which obviously 401s.

### 👟 Reproduction steps

1. In a self-hosted environment
2. Visit the Team Members page
3. Enter an email address next to "Invite" and then press invite

### 👍 Expected behavior

It should invite the user

### 👎 Actual Behavior with Screenshots

There is no visible UI feedback that an error occurred, nothing happens when pressing the button.

Using the network tab we can see that it responds with an HTTP 500 error code
<img width="761" alt="image" src="https://user-images.githubusercontent.com/13521776/200264886-a6c6273e-1553-4dcb-af6a-013c6ab0aceb.png">

Server-side, there is an ambiguous HTTP 401 error
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/13521776/200265134-00b2906b-4a5f-4158-9a7a-e83e6a2088fe.png">

### 💻 Operating system

MacOS

### 🤖 Node Version

16.x

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jfemia** [comment]
Can I clarify some behaviour here as I may have misunderstood & misconfigured some env vars -

Is a self-hosted instance always supposed to send invites via Novu cloud using the API key? Or should it also be able to send them from the self-hosted instance? (I assumed that's what the SendGrid API key was for).

Providing a valid cloud Novu API key allows my invites to send (and I now see that line in the docs), so I'm unsure whether this is a bug or by design?

**Comment by ComBarnea** [comment]
Hey @jfemia this is a bug. I am pretty sure a fix is coming in the next version of 0.9.0, @scopsy can you confirm that? And as you mentioned, there will be a need for somewhat of an API key to an Email provider, but @scopsy can elaborate a bit more.

**Comment by scopsy** [comment]
@jfemia could you please try with the new 0.9.0 release? we've no showing the invite link so you could copy it and send it manually. At this point we can't provide a working scenario with automatically sending and email because we use Novu to send messages with Novu and it will require us to expose our private key.

Hope this makes sense 🙏

**Comment by jfemia** [comment]
Hey, so we're running 0.9.0 now but we ended up just configuring it to use our novu cloud api key for sending initial invite emails. Ultimately it's not really a blocker for us so if you want to close it I'm fine with what we have.

My original assumption about this was that it was straightforward to fix - which was incorrect 😆 . I suspect a proper solution to fully decouple self-hosted from cloud is to have the invite usecase trigger a configured template directly (by adding dependencies for the stuff that triggers events), instead of using the novu client - which would also require the instance to be configured with its own sendgrid key.

**Comment by scopsy** [comment]
Thanks for the feedback @jfemia it is indeed a bit more complex than I thought too :( This mainly happens because we are trying to use Novu as much as we can while building Novu :P 

@djabarovgeorge could you please verify if the thing you worked on merged successfully and working? In this case you can close this issue 🙏

**Comment by djabarovgeorge** [comment]
Hey @jfemia, as @scopsy mentioned on the self-hosted environment we support only the manual approach. you will have two options after clicking on the `Invite` button you will be provided with a Toast that can redirect you in order to send an email, or you can copy and send the invite link personally.  please note that there was one misleading on the resend invite functionality which we already resolved and will be merged shortly.
PS. please make sure that you configure the env variable REACT_APP_DOCKER_HOSTED_ENV to be 'true'  in order to consume this functionality.
