### ISSUE TITLE
[NV-538] Change Z-index for user profile dropdown to overlay the loader in notification template screen

### ISSUE THREAD

**Issue by ainouzgali** [novuhq/novu#2198]
## **What?**

When on  [novu.co/templates](https://dev.web.novu.co/templates) , when loading the loader blocks the sign out option as seen here:

## **Fix**

Look into Z-index to overlay the dropdown over the loader.

![Screen Shot 2022-06-20 at 9.12.05.png](https://uploads.linear.app/f13f1996-c9b0-4fea-8ee7-2c3faf6a832d/ae86559a-43e2-48c8-b403-8c5d97927674/970bad7e-ef67-4bd1-8d48-ca22ac893b99)

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-538](https://linear.app/novu/issue/NV-538/change-z-index-for-user-profile-dropdown-to-overlay-the-loader-in)</sub>

**Comment by Aadarsh805** [comment]
![image](https://user-images.githubusercontent.com/95094057/207121511-16865a08-9a4c-489f-8279-9e3e3cb62394.png)
this is not the issue with the user profile dropdown as it is the same for the notification dropdown too, the issue is with the mantine loader
I checked that both the user profile and notification dropdown modal have a z-index of 300 while the loader has a z-index of 400
Couldn't figure out where to correct this

**Comment by gitstart-novu** [comment]
Here is the GitStart Ticket for this issue: https://clients.gitstart.com/novu/3271/tickets/NV-538
