### ISSUE TITLE
[NV-1650] ✨ Polishing: Remove the animation in the workflow editor

### ISSUE THREAD

**Issue by SebastianStehle** [novuhq/novu#2728]
### 📜 Description

Remove the animation in the workflow editor. It is super annoying and you have to wait like a second each time you go to the editor.

### 👍 Expected behavior

No animation

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

<sub>[NV-1650](https://linear.app/novu/issue/NV-1650/✨-polishing)</sub>

**Comment by scopsy** [comment]
@adarshajit when you move to the workflow page the nodes are slided to the center of the screen. What we want is to remove this animation just so that the node will be in the correct position without the sliding animation. 
![CleanShot 2023-02-16 at 10 53 10](https://user-images.githubusercontent.com/8872447/219315762-9a6a2e33-279e-4fa5-bb07-57005ca02e7d.gif)

**Comment by SebastianStehle** [comment]
Exactly

**Comment by joanjeremiah** [comment]
Hello! I'm interested in working on this issue. Could I please be assigned to it? Thank you!

**Comment by jainpawan21** [comment]
Hi @joanjeremiah 
This issue is already assigned

**Comment by scopsy** [comment]
Hi @adarshajit did you had a chance to take a look at this? Otherwise let me know if I can un-assign you 🙏

**Comment by scopsy** [comment]
@adarshajit the only reason could be that your server is not running correctly, do you see any errors on the console of the API?

**Comment by scopsy** [comment]
Fixed using a different UI implementation in 0.14.0
