### ISSUE TITLE
[NV-1627] New "is defined" filter for payload checks

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#3421]
## Why?

We have **Equal** and **Not Equal** filters for payload, where equality check of variable value in payload will take place. **IsDefined** filter is slightly different, as it will check whether variable value is present in payload (in case this variable is not required)

## How?

Adding another filter type to check for "truthy" values in path

<sub>From [SyncLinear.com](https://synclinear.com) | [NV-1627](https://linear.app/novu/issue/NV-1627/new-is-defined-filter-for-payload-checks)</sub>

**Comment by SergeiMeza** [comment]
I can add this

**Comment by scopsy** [comment]
Hi @SergeiMeza! Assigning you, let me know if I can help in any way. 
<img width="1272" alt="CleanShot 2023-05-16 at 08 58 02@2x" src="https://github.com/novuhq/novu/assets/8872447/383f45de-1f35-4663-9766-6aebf67f0953">

This is the area where the new version should be located, after the "IsDefined" filter type is selected, the value field should be hidden since it's not relevant any more.

**Comment by SergeiMeza** [comment]
Okay :)

**Comment by scopsy** [comment]
Hi @marooncoder09, @SergeiMeza already started to work on this and was assigned for this task 🙏

**Comment by jainpawan21** [comment]
@SergeiMeza How is it going?
Do you need any help?
