### ISSUE TITLE
[NV-2756] When switching the organization the branding information is not refetched

### ISSUE THREAD

**Issue by LetItRock** [novuhq/novu#4243]
## Reproduction Steps

1. Navigate to the Brand page, make sure you have logo or font changed from defaults and saved.
2. Change the organization.
3. The branding settings are not updated.

https://github.com/novuhq/novu/assets/2607232/8a033638-c059-409d-b4fe-1151e143226c

## Definition of done
- The branding reflects currently selected organisation.
- Display branding related to the selected organisation.

**Comment by shoaib-31** [comment]
@LetItRock Hi, please assign this issue to me, I want to work on it. I am able to reproduce the issue. However, one thing i noticed is that it only happens when we switch organisation from a existing organisation(one whose settings have been updated already) to a newer created organisation, also there is no issue when we switch from been organisations where both organisation have their settings updated(different from default).

**Comment by ainouzgali** [comment]
Thanks @shoaib-31 ! assigning you

**Comment by TheNatkat** [comment]
hey can you assign this task to me also i love to work on this project

**Comment by vishalkhoje** [comment]
Hello @ainouzgali , could you kindly assign this issue to me? I have raised a pull request to address the fixes.

**Comment by LetItRock** [comment]
hey @shoaib-31! 👋 we are looking for your PR ;)

**Comment by shoaib-31** [comment]
@LetItRock I am having trouble setting up project on my machine as I am a newbie. Thanks for assigning me, you can assign it to someone else if you want. Although, I will try to setup just for practice.

**Comment by LetItRock** [comment]
> vishalkhoje

@shoaib-31 sure, if you are having some problems please join our discord channel and open the support request there if there is no similar issue to yours ;)

**Comment by vishalkhoje** [comment]
Hello @LetItRock ,

Could you kindly consider reopening the pull request (PR)? Alternatively, should I go ahead and create a new PR for this?
