### ISSUE TITLE
[NV-3014] Unexpected provider error in Nexmo sms provider

### ISSUE THREAD

**Issue by jainpawan21** [novuhq/novu#4468]
## What?

Nexmo SMS provider is giving Unexpected provider error with all numbers

## Why? (Context)

Steps to reproduce:-

1. Go to Nexmo (Vonage) SMS API dashboard
2. Copy API Key, Api Secret and From address (id)
3. Create new nexmo integration and add above credentials, make this integration active
4. Create a workflow and add SMS step
5. trigger the workflow with a valid SMS number (make sure you are using same number you signed up on nexmo if you are in the free tier), you will see an unexpected provider error in the activity feed log without any error description
![image](https://github.com/novuhq/novu/assets/39362422/0e3951a8-d13f-4410-a389-ae45b728839d)
6. Go back to Nexmo (Vonage) dashboard, copy the example curl code that they provide to send the SMS. Hit the curl, SMS will be send successfully

It means that there is some issue in our nexmo SDK implementation in novu

## Definition of Done
Nexmo provider should work correctly and throw descriptive error in case of exception.

<sub>[NV-3014](https://linear.app/novu/issue/NV-3014/unexpected-provider-error-in-nexmo-sms-provider)</sub>

**Comment by biswajit287** [comment]
Hi @jainpawan21, I would like work on this issue. Can you please assign this to me. Thanks!

**Comment by parveshsaini** [comment]
Hey @jainpawan21! I've worked with SMS providers and have a good idea how to deal with this. It'll be much appreciated if you could assign it to me

**Comment by parveshsaini** [comment]
I've completed the issue assigned to me and have raised the PR as well. So now I'm available to work on another issue

**Comment by parveshsaini** [comment]
Okay np. Good luck @biswajit287 😊

**Comment by nick2432** [comment]
can i work on this issue?

**Comment by parveshsaini** [comment]
Hey @jainpawan21 👋
The current assignee seems inactive. Can you please assign it to me?
The issue currently assigned to me requires test credentials which Zac will provide me in few days. In the meantime, I'd like to work on this issue.

**Comment by scopsy** [comment]
Hi @biswajit287 any updates or help is needed ?

**Comment by ayushshukla7777** [comment]
hey, Can I take this issue if current assignees is inactive

**Comment by parveshsaini** [comment]
Hey 👋 @jainpawan21 @scopsy 
I've figured out how to get this done. It'll be much appreciated if you could assign it to me.

**Comment by biswajit287** [comment]
> Hi @biswajit287 any updates or help is needed ?

Hi @scopsy ,
I'm currently facing issues while trying to run the project on my system. Initially, it compiles successfully, but when I make code updates and save them, it fails to compile with an error message: The build failed because the process exited too early. This likely indicates a memory issue or a premature process termination (e.g., kill -9`).
![image](https://github.com/novuhq/novu/assets/28986622/8f8f219c-3456-44e9-b1fc-0a5b0d795044)

I'm using the following system configuration:

RAM: 16GB
Processor: AMD Ryzen 5 5500U with Radeon Graphics
Environment: WSL (Windows Subsystem for Linux)
I'm looking for guidance on the minimum system requirements needed to set up and run the project smoothly.

**Comment by jainpawan21** [comment]
@biswajit287 Could you please clean using `npm run clean` , delete all `node_modules` using npx npkill and please try again `npm run setup:project` 
It should work

**Comment by biswajit287** [comment]
hi @jainpawan21,
getting the following error when running `npm run setup:project`
``` ERR_PNPM_FETCH_404  GET https://registry.npmjs.org/@novu%2Fdal: Not Found - 404

This error happened while installing the dependencies of @novu/application-generic@0.20.0

@novu/dal is not in the npm registry, or you have no permission to fetch it.```

![image](https://github.com/novuhq/novu/assets/28986622/09ab8dfd-f6b6-41a0-be07-955bc0669b94)

**Comment by learner-mohit** [comment]
@jainpawan21 I think this issue can be closed because I checked the SMS is being sent successfully, given that one copies from, apiKey, apiSecret correctly from Vonage Dashboard.

<img width="1019" alt="Screenshot 2023-12-11 at 4 46 51 PM" src="https://github.com/novuhq/novu/assets/151846514/529d95f8-c0a7-4da5-a49f-c3603f9e57d5">

**Comment by learner-mohit** [comment]
@jainpawan21 I think this issue can be closed because I checked the SMS is being sent successfully, given that one copies from, apiKey, apiSecret correctly from Vonage Dashboard.

<img width="1019" alt="Screenshot 2023-12-11 at 4 46 51 PM" src="https://github.com/novuhq/novu/assets/151846514/529d95f8-c0a7-4da5-a49f-c3603f9e57d5">

**Comment by jainpawan21** [comment]
Thanks for the update @PaperBoardOfficial
