### ISSUE TITLE
Problem with SMS Integration through novu.co web platform

### ISSUE THREAD

**Issue by SaschaWebDev** [novuhq/novu#582]
**Describe the bug**
I have tried to integrate sms77 and nexmo through the web.novu.co panel for SMS integration, but always run into an error. 

**To Reproduce**
1. Go to web.novu.co
2. Integrate sms77 or nexmo with their API keys
3. Integrate Trigger code in own project
4. Trigger End point
5. Go into Activity Feed on web platform
6. SMS will appear with red error dot and message "Cannot read properties of null (reading 'send')"

**Expected behavior**
I should receive a working SMS through the provider or receive an error message that provides me with useful information of what was wrong with my request, like "API key wrong" or "FROM not allowed/verified".

**Screenshots**
![image](https://user-images.githubusercontent.com/19645465/169515190-a1209507-ccb8-43ea-a2b9-0c1d5ea71f75.png)

**Details (please complete the following information):**
 - OS: Windows
 - Next.js 12.1.6

**Additional context**
I have entered the correct API keys and used different variations for "from" like name or my real phone number. Also I have verified my phone number on sms77 and bought a belgium phone number for sender on nexmo. I have just used one SMS integration provider at any given time. My emails are coming through with Mailjet, but no SMS is working. Also why does Novu require "FROM" sender for sms77 integration provider when their documentation states that this value is optional?

**Comment by scopsy** [comment]
Thank you for the detailed report! 

I think I have a clue to might what has happened: 
https://github.com/novuhq/novu/blob/caeb2aab7413b5b79dccd5778c21df1dc83f9a3e/apps/api/src/app/events/services/sms-service/handlers/sms77.handler.ts#L8

Looking at the provider handler implementation `sns` is passed to the `constructur` call. Looks like a mistake and `sms77` should be passed there. 

Not sure if this will fix nexmo as well, since I don't see a handler for it there. @djabarovgeorge what do you think?

**Comment by SaschaWebDev** [comment]
I have opened a PR [here ](https://github.com/novuhq/novu/pull/584)

**Comment by djabarovgeorge** [comment]
Hey @scopsy,
You are right we need a provider handler in order to map the credentials, so nexmo needs one as well.

**Comment by Nike682631** [comment]
@scopsy  Is this issue available to work on?

**Comment by scopsy** [comment]
Hi @Nike682631 this was already fixed 🙏
