### ISSUE TITLE
CTA not working - NextJs

### ISSUE THREAD

**Issue by singhgulshan** [novuhq/novu#605]
**Describe the bug**
CTA for notification not working

**To Reproduce**
1. Create In-App Notification template with redirect url
2. Trigger notification
3. Clicking on notification does not redirect to desired page

**Expected behavior**
It should redirect to desired page.

**Details:**
 - OS: Mac M1
 - Node Version: v14.18.3
 - NPM Version: 8.10.0
 - @novu/notification-center: 0.4.0
 - react: 17.0.2
 - next: 12.0.2

**Comment by scopsy** [comment]
Thanks for reporting @singhgulshan i've just noticed that since our move to the standalone notification library the CTA navigation was not well documented. I will make sure to add this to the docs part.

For now you can use the `onNotificationClick` prop from the NotificationCenter component the data passed to it can be used to navigate to the new page using your framework of choice navigation paradigm.

```tsx

<NovuProvider
  applicationIdentifier={props.applicationIdentifier as string}
  subscriberId={userDataPayload.subscriberId}>
  <NotificationCenter onNotificationClick={props.onNotificationClick} />
</NovuProvider>

export function onNotificationClick(notification: IMessage) {
  navigate(notification.cta.data.url);
}
```

**Comment by singhgulshan** [comment]
@scopsy thanks for the solution. Also, useNotification hooks is not working. i was getting empty array for the notifications also useSocket was returning null. Hope you can provide the solution for this also. Thanks in advance.

**Comment by djabarovgeorge** [comment]
Hey @singhgulshan 
Excuse me for joining late, but could you present some snipped of the issue of useNotification returning empty array and null socket? so we could address your issue.

My guess is that you are not waiting for the response to get to the client and the data is not yet fetched and socked still not initialized.

Please let us know if you still experiencing any issues.

**Comment by singhgulshan** [comment]
@djabarovgeorge This is the code snippet i'm using.
![carbon](https://user-images.githubusercontent.com/36273489/171096532-2d0a9442-e622-47a5-b5d0-689098b075bd.png)

Also when i call `fetchNextPage` or `refetch` following error occurs.
**TypeError: Cannot read properties of null (reading 'getNotificationsList')**
<img width="971" alt="Screenshot 2022-05-31 at 10 36 38 AM" src="https://user-images.githubusercontent.com/36273489/171096845-590e2921-776d-48af-933d-b61fa464b3b9.png">

**Comment by djabarovgeorge** [comment]
Hey @singhgulshan 
Thank you for taking your time in order to present a snippet 😊  , from the snippet and the second error `TypeError: Cannot read properties of null (reading 'getNotificationsList')`  i can conclude that you are not wrapping your component with NovuProvider component that is mentioned in the documentation, please let me know it is a correct conclusion or is it missing from the snippet.

https://docs.novu.co/docs/notification-center/getting-started

You need to enter into NovuProvider component your and the subscriberId and applicationIdentifier, so that useNotifications and its API Client can be initialized before you get the data.

**Comment by singhgulshan** [comment]
@djabarovgeorge its working after NovuProvider, my bad. 
But i cannot see the payload in the notification which i have sent from backend, is this expected behavior??

**Comment by djabarovgeorge** [comment]
No worries we here to help 😊. 

Regarding the missing notifications, it is not expected. 
In order to examine the issue first of all we need to validate two things: 
1. Subscriber - make sure you use the same subscriber id when you send the notification and when you initialize the NovuProvider component. 
2. Environment - We need to make sure we use the same one. If you send to Novus cloud environment endpoint you should see the notification. However if you send into your own environment endpoint you need you need to pass to the NovuProvider your backendUrl endpoint (the default is Novu's cloud). 
As mentioned on the link below in section "Use your own backend and socket url"

https://docs.novu.co/docs/notification-center/react-components

Please let us know if it helps you to resolve your issue.

**Comment by singhgulshan** [comment]
I think i was not clear in above query.
I'm getting all the notifications, none of the notification is getting missed. I will make it clear with one example.
Suppose i'm triggered one notification with following payload:
```
Novu.trigger(
"template-id",
   {
       to:"subscriber-id",
       payload : { someKey : "Some data" }
   }
 )
```
but in notification ` payload : { someKey : 'Some data' }` is not present.
I hope i'm clear this time.

**Comment by singhgulshan** [comment]
Yes, m using double curly brackets for some of the variables, but it will be better if we can pass this payload to notification so that we can handle some UI requirement accordingly. Just a enhancement request.

**Comment by scopsy** [comment]
This is a great suggestion @singhgulshan  actually needed this aswell for myself a couple of days back. I will create an issue for this so we can collaborate on it there.

**Comment by scopsy** [comment]
@singhgulshan created #612 let me know if this is what you had in mind aswell

**Comment by scopsy** [comment]
Added the explanation on the Docs site for the onNotificationClick prop, closing this for now.
